image: python:3.7

stages:
  - build
  - test
  - deploy

before_script:
  - date
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt 

Echo:
  stage: build
  script: cat application.py utils.py > compiled.py
  artifacts:
    paths:
      - compiled.py
    expire_in: 20 minutes

Test Py3.4:
  image: python:3.4
  stage: test
  script: pytest -v

Test Py3.5:
  image: python:3.5
  stage: test
  script: pytest -v

Test Py3.6:
  image: python:3.6
  stage: test
  script: pytest -v

Test Py3.7:
  image: python:3.7
  stage: test
  script: pytest -v

Deploying:
  stage: deploy
  image: alpine
  script: cat compiled.py | gzip > package.gz
  when: manual
  artifacts:
    paths:
      - package.gz

after_script:
  - date