image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


stages:
  - build
  - test
  - deploy

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt 

job 1:
  stage: build
  script: echo "Building..."

job 2:
  stage: test
  script: pytest -v

job 3:
  stage: deploy
  script: echo "Deploying..."

after_script:
  - echo OK!!